### ISSUE TITLE
6.1.4.3 Suggestion: change text and remove significant burden 

### ISSUE THREAD

**Issue by damienbod** [oauth-wg/oauth-browser-based-apps#25]
6.1.4.3. 

_Additionally, this pattern requires all interactions between the JavaScript application and the resource servers to be proxied by the BFF, which puts a significant burden on the server-side component._

I usually use the BFF architecture without requiring a downstream API or a resource server and thus no proxy is required.  My server logic is deployed as part of the BFF server application.

**Comment by aaronpk** [comment]
That sounds like that falls under the "Not Using OAuth" model: https://www.ietf.org/archive/id/draft-ietf-oauth-browser-based-apps-15.html#name-single-domain-browser-based

**Comment by damienbod** [comment]
Hi @aaronpk yes it does sound like this, but I'm a bit confused because this is in the "Discouraged and Deprecated Architecture Patterns" 

This is in effect the BFF without a downstream API. If I need a downstream API, then I add a proxy and request the scope when required. I see the proxy, downstream API as a add-o to the BFF.

**Comment by aaronpk** [comment]
Can you elaborate on that? Are you using OIDC only for user authentication, e.g. no access tokens involved then? I'm trying to figure out how your use of OIDC/OAuth fits in when there is no API.

**Comment by damienbod** [comment]
Yes. The UI and the backend are authenticated as one using OIDC. The session is stored in the form of a cookie as described in the doc. The APIs uses cookie authentication like the BFF. The backend APIs implement the BL directly and there is not need for further API calls to different domains. Authz still needs a solution. If I need to use separate APIs on different domains, then I implement OAuth and add new scopes as required. At this point I would add the proxy, or just implement a Http Client. I don't always require a delegated user access token for the downstream APIs.

So this is the BFF pattern described in section 6.1.1. The resource server part is not separated "always" from the BFF part, only when required.

**Comment by philippederyck** [comment]
@aaronpk This discussion is related to our discussion when we restructured the document. The "no oauth" model is indeed valid and would just rely on a session between the frontend and the "API" to keep track of user's authentication state.

Back then, we weren't sure if this was discouraged, but agreed that it is not a core pattern of this spec, since it focuses on API-access with access tokens.

Two options: Either we rename this entire section (not my favorite), or we move the "no oauth" pattern upwards to section 4.

Let me know what you think

**Comment by aaronpk** [comment]
This sounds like what's described [in 6.1.2.4](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#section-6.1.2.4)

> an application relying on both internal and external resource servers can choose to host the internal resource server alongside the BFF. In that scenario, requests to the internal resource server are handled directly at the BFF, without the need to proxy requests over the network.

The intent of the "significant burden" line is to capture the difficulty in deploying this pattern at scale. Perhaps there is a better way to phrase it. The same difficulty applies whether the resource server is internal to the backend or if it calls external resources. The point is you have to deal with either more network traffic or doing things like geographically distributing your databases.

**Comment by philippederyck** [comment]
I have [proposed](https://github.com/oauth-wg/oauth-browser-based-apps/pull/36)  a slight rewording to resolve this issue according to comments made by @aaronpk and @damienbod

**Comment by aaronpk** [comment]
Thank you, closing as PR #36 resolves this.
