### ISSUE TITLE
security advantage BFF makes nonce based CSP possible

### ISSUE THREAD

**Issue by damienbod** [oauth-wg/oauth-browser-based-apps#27]
I'm not sure where this belongs, but I think it would be good to add it. 

Because the BFF APIs and the UI can be hosted in the same application, it is easy  to implement a nonce based CSP for the UI scripts and styles. Modern JS framework now support this. This is very easy to implement when using BFF security architecture where the same application is used to host the APIs and the UI .

**Comment by philippederyck** [comment]
The use of CSP nonces requires the ability to insert a fresh nonce on every page load. 

While this is indeed possible by hosting the HTML page of the frontend application (SPA) on the BFF, it is not required to deploy a frontend this way. It is a perfectly valid pattern to deploy the SPA on a CDN and have it call the dynamic BFF component. In that case, nonces would not work, but hashes might.

Given that this advice is highly specific for CSP and less related to the BFF pattern, I'd opt to not go into these details in this spec.
