### ISSUE TITLE
Add architectural pattern of using a Service Worker as the OAuth client

### ISSUE THREAD

**Issue by aaronpk** [oauth-wg/oauth-browser-based-apps#3]
keeps the access token and refresh token out of the DOM-accessible JS, only accessible from within the Service Worker

https://gitlab.com/jimdigriz/oauth2-worker

**Comment by aaronpk** [comment]
Done in #19

**Comment by jimdigriz** [comment]
> https://gitlab.com/jimdigriz/oauth2-worker

For the history books, now at https://github.com/jimdigriz/oauth2-worker
