### ISSUE TITLE
Consistently use *applications* or *apps*

### ISSUE THREAD

**Issue by philippederyck** [oauth-wg/oauth-browser-based-apps#42]
In his review, Justin Richer pointed out that the spec inconsistently uses both the term *applications* and *apps* in the title and the document. It makes sense to settle for one and be consistent about it. 

My vote goes to *applications*, which is most common in the context of web applications. *Apps* is more related to native/mobile apps. 

A quick Google search on *Angular apps* vs *Angular applications* or *js apps* vs *js applications* also indicates that applications is more common. 

When not updating, include *applications* vs *apps* in the terminology section.

**Comment by aaronpk** [comment]
+1 for "applications"
