### ISSUE TITLE
Working Group Last Call

### ISSUE THREAD

**Issue by aaronpk** [oauth-wg/oauth-browser-based-apps#51]
This is a placeholder issue for working group last call comments. If you have any minor comments, feel free to add them below. If you have reviewed the draft and have no comments, please note below that you are happy with the current draft! If you have any substantial comments, feel free to open them as a new issue.

**Comment by rossajmcd** [comment]
Looks good to me, thanks for all the hard work.

**Comment by aaronpk** [comment]
Thanks, closing this as the Working Group Last Call has finished, and the shepherd writeup is now in progress
