### ISSUE TITLE
Proposed flow for using DPoP with token mediating backend

### ISSUE THREAD

**Issue by vivshankar** [oauth-wg/oauth-browser-based-apps#54]
Thank you for proposing the OAuth Browser Based Apps spec. I have been thinking specifically about the token mediating backend and wanted to propose a method to use DPoP to secure the token usage.

## Goal

- Use DPoP as a mechanism to provide proof of possession when making use of the access token exposed on the untrusted user agent.

- Prevent an attacker who is able to inject JS in the browser to leverage a SSO session and use their own key-pair to present a DPoP proof to obtain a token.

## Possible approach

**New session and no token**

1. `Frontend client` generates a DPoP proof.

2. `Frontend client` requests for a new token from the `Token Mediating Backend` (also called Token Mediator below). As part of this, the DPoP proof is included as a dpop header.

3. `Token Mediator` checks that there is no existing session for this browser, so it kicks off a new authcode flow. Auth code flow kicked off with PKCE.

4. Browser is redirected to the authorize endpoint. User performs authentication and consent. The authcode is generated and included in the redirect back to Token Mediator callback endpoint.

5. `Token Mediator` calls the token endpoint with the authcode, DPoP proof (provided by the front-end), and a strong client auth method like private_key_jwt.

6. `Token mediator` recieves and stores the refresh token in a session-bound cache, _along with the the jkt associated with the DPoP proof (effectively binding the client to the session)_. The access token is returned to the Frontend client.

7. `Frontend client` uses the access token as needed. It will need to include a signed DPoP proof when calling the resource endpoints.

**Expired token**

1. Frontend client generates a DPoP proof signed using the same private key that is used when establishing the token mediator session.

2. Frontend client calls the get-token API on the Token Mediator with the DPoP proof.

3. Token Mediator validates that the jkt matches the one in the session.

4. Token Mediator kicks off a refresh token flow or a new auth code flow (if the refresh token has expired).

**Threat model**

By binding the jkt associated with the DPoP proof to the session, the session is “bound” to the client. Possible threats:

1. Attacker injects JS on a client with no session and uses a generated key-pair for the DPoP proof: This leads the user through an authentication, authorization and consent flow, which can be used to mitigate this attack vector. However, there is no real way to prevent this attack if the JS executes before the app requests for the token. In this scenario, when the app does request the token, the flow will fail and the user will see an error message, indicating a possible compromise. Appropriate remediation action can be taken at this point to, for example, log the user out with an appropriate message.

2. Attacker injects JS after the client has established a session with the mediating backend: Since the session is bound to the jkt of the key used to sign the DPoP proof, this attack will fail.

I was hoping to get some thoughts on this proposed approach. This is specifically to solicit opinions for a plausible implementation to address https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#section-6.2.4.3.2.

**Comment by PhilippeDeRyck-Xenit** [comment]
This scenario gives you the benefits of DPoP by having a sender-constrained access token. However, I don't see anything here that significantly changes the security properties of a Token Mediating Backend scenario. 


> 2. Attacker injects JS after the client has established a session with the mediating backend: Since the session is bound to the jkt of the key used to sign the DPoP proof, this attack will fail.

When this happens, the attacker's code runs in the same execution environment as the frontend's code. So if the frontend has a way to obtain a new access token from the backend, so does the attacker (just like with a BFF, an attacker could send requests to the BFF).

In your specific scenario, the attacker would re-use the existing session between the browser and the backend to request a token associated with the initial DPoP proof. It also implies that the attacker can only abuse that token with valid DPoP proofs, which can be obtained through the so-called "online attack".

Based on some wordings (binding a client to a session), it seems that at least part of the attack vector is a session hijacking attack, which is not the same as running malicious JS in the application's execution context in the victim's browser.

**Comment by philippederyck** [comment]
This scenario gives you the benefits of DPoP by having a sender-constrained access token. However, I don't see anything here that significantly changes the security properties of a Token Mediating Backend scenario. 


> 2. Attacker injects JS after the client has established a session with the mediating backend: Since the session is bound to the jkt of the key used to sign the DPoP proof, this attack will fail.

When this happens, the attacker's code runs in the same execution environment as the frontend's code. So if the frontend has a way to obtain a new access token from the backend, so does the attacker (just like with a BFF, an attacker could send requests to the BFF).

In your specific scenario, the attacker would re-use the existing session between the browser and the backend to request a token associated with the initial DPoP proof. It also implies that the attacker can only abuse that token with valid DPoP proofs, which can be obtained through the so-called "online attack".

Based on some wordings (binding a client to a session), it seems that at least part of the attack vector is a session hijacking attack, which is not the same as running malicious JS in the application's execution context in the victim's browser.

**Comment by vivshankar** [comment]
Thanks @philippederyck . The attacker wouldn't have access to the same key-pair used to sign the DPoP proof? This assumes the use of appropriate security best practices to maintain a non-exportable private key.

**Comment by philippederyck** [comment]
The private key would indeed be non-exportable, which means neither the frontend nor the attacker has access to it. However, the frontend has a way to obtain a signed DPoP proof to make API calls. Once the attacker gains a foothold, they can now use that exact same mechanism to request a DPoP proof for a malicious API call.

**Comment by vivshankar** [comment]
My proposal is banking on needing user interaction (in the form of authentication and consent) to obtain a session on the token mediating backend. Given the first invocation records the jkt in the session (possibly mapped to the client_id), the attacker using their own jkt on the same browser session will result in a failure. So, session hijacking is covered with this approach. Similarly subsequent token requests are covered as well.

**Comment by philippederyck** [comment]
You are missing the point. There is no session hijacking (i.e., extracting the user's session), but the attacker takes control of the existing client (i.e., executing malicious code within the client within the victim's browser).

As explained in the intro of [section 5](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#name-the-threat-of-malicious-jav), the attacker's code has the same privileges as the legitimate frontend client. So when you write `Frontend client generates a DPoP proof signed using the same private key that is used when establishing the token mediator session.`, you have to assume that the attacker can perform those exact same steps. 

This type of attack is also explicitly covered in [the DPoP spec](https://datatracker.ietf.org/doc/html/rfc9449#name-untrusted-code-in-the-clien).

**Comment by aaronpk** [comment]
I believe that section 5 and the DPoP spec are sufficient to demonstrate why this proposal doesn't change anything about the security properties.

**Comment by vivshankar** [comment]
@aaronpk @philippederyck Thanks for taking the time.

The purpose of my post was to ask if the approach laid out in this proposal is an acceptable implementation pattern for [section 6.2.4.3.2](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps#section-6.2.4.3.2). I realize we went a bit afield to that original goal, mostly because of how I phrased the threat model.

My proposal is weird in the sense that the party producing the DPoP proof is not the OAuth client (which lives in the token mediating backend) but the token is ultimately used by the party to call into resource APis. Do you see any concerns with the approach that I have put here?
