### ISSUE TITLE
Discussing ID tokens in the Implicit flow deprecation section

### ISSUE THREAD

**Issue by philippederyck** [oauth-wg/oauth-browser-based-apps#59]
Rifaat Shekh-Yusef mentioned the following in a review (mail 13/11/2024):

> Section 7.2.4
> “Performing OpenID Connect using the Authorization Code grant type provides the benefit of the client not needing to verify the JWT signature, …”
> With all kinds of middle boxes being used these days, should we encourage people to verify the JWT signature even if it was obtained over an HTTPS channel?

Good question, but it has me wondering why are we talking about OIDC in this spec at all? I would recommend to drop this paragraph.

**Comment by aaronpk** [comment]
There are several other mentions of OpenID Connect in the document, but this is the only one that gets in to the specifics of OIDC, so I agree we should just drop this paragraph.
